name: Deploy .NET Lambda

on:
  push:
    branches:
      - main
    paths:
      - "API/**"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install Lambda Tools
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Add Lambda tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore
        run: dotnet restore ./API/API.csproj

      - name: Deploy to AWS Lambda
        run: |
          dotnet lambda deploy-serverless \
            --project-location ./API \
            --stack-name ${{ secrets.AWS_STACK_NAME }} \
            --region ${{ secrets.AWS_REGION }} \
            --s3-bucket ${{ secrets.AWS_S3_BUCKET }} \
            --s3-prefix ${{ secrets.AWS_S3_PREFIX }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
